create table Person(
                       id int primary key generated by default as identity,
                       name varchar(100) not null,
                       age int check ( age < 100 ),
                       email varchar(100)
);

insert into Person values (1, 'Bob', 28, 'bob@mail.ru'),
                          (2, 'Tom', 38, 'tom@mail.ru'),
                          (3, 'Mike', 52, 'mike@yahoo.com'),
                          (4, 'Kate', 32, 'kate@gmail.com'),
                          (5, 'Layla', 31, 'layla@yandex.ru');

alter table Person add column email varchar(100) unique;

drop table Person cascade;